Traceback (most recent call last):
  File "/content/MDMM/train.py", line 136, in <module>
    main()
  File "/content/MDMM/train.py", line 108, in main
    losses_graph["train_loss"], losses_graph["train_rec"], losses_graph["train_gauss"], losses_graph["train_cat"], losses_graph["train_acc"], losses_graph["train_nmi"] = model.train_epoch_GMVAE(optimizer, train_loader)
  File "/content/MDMM/model.py", line 480, in train_epoch_GMVAE
    unlab_loss_dic = self.unlabeled_loss(data, out_net)
  File "/content/MDMM/model.py", line 533, in unlabeled_loss
    loss_rec = loss_functions.reconstruction_loss(data, data_recon) # data: tensore, data_recon: stringa
  File "/content/MDMM/GMVAE.py", line 244, in reconstruction_loss
    loss = (real - predicted).pow(2)
RuntimeError: The size of tensor a (139968) must match the size of tensor b (216) at non-singleton dimension 3